In [16]:
import numpy as np
import pandas as pd

Đọc dữ liệu của tệp tin CSV và in ra thông tin cơ bản về DataFrame

In [17]:
df = pd.read_csv('Crawl_Datailovelotteria.csv')
Clean_data_df = pd.read_csv('Crawl_Datailovelotteria.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 51 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   post_id                        940 non-null    int64
 1   text                           894 non-null    object
 2   post_text                      894 non-null    object
 3   shared_text                    7 non-null      object
 4   original_text                  0 non-null      float64
 5   time                           940 non-null    object
 6   timestamp                      930 non-null    float64
 7   image                          820 non-null    object
 8   image_lowquality               940 non-null    object
 9   images                         908 non-null    object
 10  images_description             908 non-null    object
 11  images_lowquality              940 non-null    object
 12  images_lowquality_description  940 non-null    object
 13  video                          79 non-null     object
 14  video_duration_seconds         0 non-null      float64
 15  video_height                   0 non-null      float64
 16  video_id                       79 non-null     float64
 17  video_quality                  0 non-null      float64
 18  video_size_MB                  0 non-null      float64
 19  video_thumbnail                79 non-null     object
 20  video_watches                  0 non-null      float64
 21  video_width                    0 non-null      float64
 22  likes                          808 non-null    float64
 23  comments                       940 non-null    int64
 24  shares                         940 non-null    int64
 25  post_url                       940 non-null    object
 26  link                           328 non-null    object
 27  links                          913 non-null    object
 28  user_id                        940 non-null    int64
 29  username                       940 non-null    object
 30  user_url                       940 non-null    object
 31  is_live                        940 non-null    bool
 32  factcheck                      0 non-null      float64
 33  shared_post_id                 1 non-null      float64
 34  shared_time                    1 non-null      object
 35  shared_user_id                 1 non-null      float64
 36  shared_username                1 non-null      object
 37  shared_post_url                1 non-null      object
 38  available                      940 non-null    bool
 39  comments_full                  940 non-null    object
 40  reactors                       132 non-null    object
 41  w3_fb_url                      132 non-null    object
 42  reactions                      132 non-null    object
 43  reaction_count                 940 non-null    int64
 44  with                           28 non-null     object
 45  page_id                        940 non-null    int64
 46  sharers                        0 non-null      float64
 47  image_id                       753 non-null    float64
 48  image_ids                      940 non-null    object
 49  was_live                       940 non-null    bool
 50  fetched_time                   132 non-null    object
dtypes: bool(3), float64(15), int64(6), object(27)
memory usage: 355.4+ KB

In [18]:
# Loại bỏ các hàng trùng lặp trong DataFrame
Clean_data_df = Clean_data_df.drop_duplicates()
# Loại bỏ các cột trùng lặp sau khi chuyển vị DataFrame
Clean_data_df = Clean_data_df.T.drop_duplicates().T
# Loại bỏ các cột có tất cả giá trị là NaN (không có giá trị nào khác NaN)
Clean_data_df = Clean_data_df.dropna(axis=1, how='all')
Clean_data_df.info()
# Đưa ra file clean_data
Clean_data_df.to_csv('clean_data.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 41 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   post_id                        940 non-null    object
 1   text                           894 non-null    object
 2   post_text                      894 non-null    object
 3   shared_text                    7 non-null      object
 4   time                           940 non-null    object
 5   timestamp                      930 non-null    object
 6   image                          820 non-null    object
 7   image_lowquality               940 non-null    object
 8   images                         908 non-null    object
 9   images_description             908 non-null    object
 10  images_lowquality              940 non-null    object
 11  images_lowquality_description  940 non-null    object
 12  video                          79 non-null     object
 13  video_id                       79 non-null     object
 14  video_thumbnail                79 non-null     object
 15  likes                          808 non-null    object
 16  comments                       940 non-null    object
 17  shares                         940 non-null    object
 18  post_url                       940 non-null    object
 19  link                           328 non-null    object
 20  links                          913 non-null    object
 21  user_id                        940 non-null    object
 22  username                       940 non-null    object
 23  user_url                       940 non-null    object
 24  is_live                        940 non-null    object
 25  shared_post_id                 1 non-null      object
 26  shared_time                    1 non-null      object
 27  shared_user_id                 1 non-null      object
 28  shared_username                1 non-null      object
 29  shared_post_url                1 non-null      object
 30  available                      940 non-null    object
 31  comments_full                  940 non-null    object
 32  reactors                       132 non-null    object
 33  w3_fb_url                      132 non-null    object
 34  reactions                      132 non-null    object
 35  reaction_count                 940 non-null    object
 36  with                           28 non-null     object
 37  page_id                        940 non-null    object
 38  image_id                       753 non-null    object
 39  image_ids                      940 non-null    object
 40  fetched_time                   132 non-null    object
dtypes: object(41)
memory usage: 301.2+ KB

In ra reactions

In [19]:
unique_reactions = Clean_data_df['reactions'].unique()[:100]
unique_reactions

array(["{'thích': 33, 'yêu thích': 9, 'haha': 2, 'wow': 2}",
       "{'thích': 179, 'yêu thích': 76, 'wow': 1, 'thương thương': 9, 'buồn': 3}",
       "{'thích': 11, 'yêu thích': 1, 'haha': 2, 'wow': 1}",
       "{'thích': 49, 'yêu thích': 7, 'thương thương': 1}",
       "{'thích': 472, 'yêu thích': 17, 'wow': 2, 'thương thương': 1, 'buồn': 1}",
       "{'thích': 485, 'yêu thích': 39, 'thương thương': 3}",
       "{'thích': 30, 'yêu thích': 6, 'thương thương': 1}",
       "{'thích': 89, 'yêu thích': 4, 'phẫn nộ': 1}",
       "{'thích': 455, 'yêu thích': 14, 'haha': 3}",
       "{'thích': 222, 'yêu thích': 5, 'buồn': 1}",
       "{'thích': 3826, 'yêu thích': 8, 'wow': 2, 'buồn': 1}",
       "{'thích': 38, 'yêu thích': 9, 'buồn': 1}",
       "{'thích': 423, 'yêu thích': 28, 'wow': 1, 'thương thương': 1, 'phẫn nộ': 1}",
       "{'thích': 423, 'yêu thích': 10, 'wow': 1, 'thương thương': 2}",
       "{'thích': 137, 'yêu thích': 13, 'wow': 2, 'thương thương': 1, 'buồn': 1}",
       "{'thích': 439, 'yêu thích': 30, 'haha': 1, 'thương thương': 1, 'buồn': 1}",
       "{'thích': 496, 'yêu thích': 51, 'haha': 2, 'wow': 5, 'thương thương': 1}",
       "{'thích': 27, 'yêu thích': 4, 'haha': 1, 'thương thương': 1}",
       "{'thích': 194, 'yêu thích': 11, 'haha': 1}",
       "{'thích': 409, 'yêu thích': 24, 'haha': 1, 'thương thương': 1}",
       "{'thích': 407, 'yêu thích': 17, 'wow': 1, 'buồn': 1}",
       "{'thích': 426, 'yêu thích': 21}",
       "{'thích': 412, 'yêu thích': 14, 'haha': 72, 'thương thương': 1, 'phẫn nộ': 1}",
       "{'thích': 498, 'yêu thích': 31, 'haha': 1, 'buồn': 1}",
       "{'thích': 16, 'yêu thích': 2}",
       "{'thích': 30, 'yêu thích': 5, 'thương thương': 1}",
       "{'thích': 469, 'yêu thích': 19, 'haha': 1, 'buồn': 1}",
       "{'thích': 36, 'yêu thích': 7, 'thương thương': 1}",
       "{'thích': 525, 'yêu thích': 16, 'haha': 2, 'wow': 2}",
       "{'thích': 91, 'yêu thích': 6, 'haha': 2, 'buồn': 2}",
       "{'thích': 74, 'yêu thích': 8, 'thương thương': 3}",
       "{'thích': 100, 'yêu thích': 11, 'thương thương': 2}",
       "{'thích': 542, 'yêu thích': 38, 'haha': 1, 'thương thương': 1}",
       "{'thích': 397, 'yêu thích': 11, 'haha': 3, 'thương thương': 1}",
       "{'thích': 397, 'yêu thích': 15, 'haha': 1, 'wow': 1, 'thương thương': 1}",
       "{'thích': 444, 'yêu thích': 26, 'thương thương': 2}",
       "{'thích': 78, 'yêu thích': 17, 'thương thương': 2}",
       "{'thích': 40, 'yêu thích': 3, 'thương thương': 2}",
       "{'thích': 561, 'yêu thích': 40, 'haha': 3, 'wow': 1, 'thương thương': 1}",
       "{'thích': 146, 'yêu thích': 6, 'thương thương': 1}",
       "{'thích': 460, 'yêu thích': 31, 'haha': 1, 'thương thương': 1}",
       "{'thích': 2964, 'yêu thích': 5}",
       "{'thích': 550, 'yêu thích': 3, 'thương thương': 1}",
       "{'thích': 1208, 'yêu thích': 24, 'haha': 2, 'thương thương': 2}",
       "{'thích': 1107, 'yêu thích': 17, 'haha': 1, 'buồn': 1}",
       "{'thích': 806, 'yêu thích': 5, 'haha': 143, 'wow': 1, 'thương thương': 2, 'buồn': 2}",
       "{'thích': 913, 'yêu thích': 11, 'wow': 1, 'thương thương': 1}",
       "{'thích': 936, 'yêu thích': 32, 'thương thương': 1}",
       "{'thích': 706, 'yêu thích': 2, 'haha': 1}",
       "{'thích': 825, 'yêu thích': 9, 'buồn': 6, 'phẫn nộ': 1}",
       "{'thích': 1216, 'yêu thích': 17, 'wow': 1, 'thương thương': 2}",
       "{'thích': 1200, 'yêu thích': 10, 'wow': 1, 'thương thương': 1}",
       "{'thích': 1093, 'yêu thích': 17, 'haha': 1, 'thương thương': 3}",
       "{'thích': 729, 'yêu thích': 6, 'thương thương': 1}",
       "{'thích': 944, 'yêu thích': 16, 'thương thương': 1, 'buồn': 1, 'phẫn nộ': 1}",
       "{'thích': 946, 'yêu thích': 23, 'wow': 1, 'thương thương': 1}",
       "{'thích': 667, 'yêu thích': 9, 'wow': 2, 'thương thương': 1}",
       "{'thích': 932, 'yêu thích': 22, 'wow': 1}",
       "{'thích': 737, 'yêu thích': 2, 'haha': 1}",
       "{'thích': 29, 'yêu thích': 3, 'thương thương': 1}",
       "{'thích': 3790, 'yêu thích': 22, 'haha': 3, 'wow': 1, 'thương thương': 1, 'phẫn nộ': 1}",
       "{'thích': 926, 'yêu thích': 15, 'haha': 1, 'wow': 1, 'thương thương': 1}",
       "{'thích': 959, 'yêu thích': 14, 'haha': 1, 'wow': 1, 'thương thương': 1}",
       "{'thích': 933, 'yêu thích': 17, 'wow': 1, 'thương thương': 2}",
       "{'thích': 594, 'yêu thích': 11, 'thương thương': 1}",
       "{'thích': 546, 'yêu thích': 3, 'haha': 1, 'thương thương': 1}",
       "{'thích': 1016, 'yêu thích': 15, 'haha': 1}",
       "{'thích': 990, 'yêu thích': 16, 'haha': 1, 'phẫn nộ': 1}",
       "{'thích': 870, 'yêu thích': 28, 'thương thương': 2}",
       "{'thích': 984, 'yêu thích': 7, 'thương thương': 1}",
       "{'thích': 567, 'yêu thích': 8, 'thương thương': 2}",
       "{'thích': 51, 'yêu thích': 2, 'thương thương': 1}",
       "{'thích': 913, 'yêu thích': 8, 'haha': 54, 'thương thương': 2}",
       "{'thích': 726, 'yêu thích': 3}",
       "{'thích': 534, 'yêu thích': 4, 'thương thương': 1}",
       "{'thích': 715, 'yêu thích': 1, 'wow': 1}",
       "{'thích': 171, 'yêu thích': 9, 'thương thương': 1}",
       "{'thích': 923, 'yêu thích': 13, 'wow': 2, 'thương thương': 3}",
       "{'thích': 984, 'yêu thích': 12, 'thương thương': 1}",
       "{'thích': 755, 'yêu thích': 7, 'haha': 1, 'thương thương': 1}",
       "{'thích': 1056, 'yêu thích': 16, 'haha': 1, 'thương thương': 2}",
       "{'thích': 1135, 'yêu thích': 28, 'wow': 1}",
       "{'thích': 2003, 'yêu thích': 12, 'haha': 3}",
       "{'thích': 1465, 'yêu thích': 23, 'haha': 1, 'wow': 3, 'thương thương': 2, 'buồn': 1}",
       "{'thích': 1119, 'yêu thích': 34, 'thương thương': 1}",
       "{'thích': 947, 'yêu thích': 8, 'thương thương': 1}",
       "{'thích': 873, 'yêu thích': 2, 'thương thương': 1}",
       "{'thích': 1066, 'yêu thích': 17, 'wow': 2, 'thương thương': 1}",
       "{'thích': 851, 'yêu thích': 14, 'thương thương': 3}",
       "{'thích': 772, 'yêu thích': 74, 'haha': 5, 'wow': 2, 'thương thương': 4, 'buồn': 2}",
       "{'thích': 695, 'yêu thích': 17, 'haha': 1, 'thương thương': 2}",
       "{'thích': 761, 'yêu thích': 10, 'wow': 2}",
       "{'thích': 666, 'yêu thích': 20}",
       "{'thích': 806, 'yêu thích': 30, 'wow': 1, 'thương thương': 1}",
       "{'thích': 856, 'yêu thích': 48, 'haha': 1, 'wow': 1, 'thương thương': 2, 'phẫn nộ': 1}",
       "{'thích': 716, 'yêu thích': 8}",
       "{'thích': 702, 'yêu thích': 11, 'thương thương': 1}",
       "{'thích': 695, 'yêu thích': 89, 'haha': 4, 'wow': 1, 'thương thương': 2, 'buồn': 2, 'phẫn nộ': 1}",
       "{'thích': 620, 'yêu thích': 13, 'wow': 1, 'thương thương': 3}",
       "{'thích': 648, 'yêu thích': 9, 'haha': 1, 'wow': 2, 'thương thương': 1, 'buồn': 3}"],
      dtype=object)

In ra post_id, reactions

In [20]:
df_reactions = df[['post_id', 'reactions']][:100]
df_reactions

            post_id                                          reactions
0   739295874894410  {'thích': 33, 'yêu thích': 9, 'haha': 2, 'wow'...
1   738821911608473  {'thích': 179, 'yêu thích': 76, 'wow': 1, 'thư...
2   739177558239575  {'thích': 11, 'yêu thích': 1, 'haha': 2, 'wow'...
3   737074941783170  {'thích': 49, 'yêu thích': 7, 'thương thương': 1}
4   736899418467389  {'thích': 472, 'yêu thích': 17, 'wow': 2, 'thư...
..              ...                                                ...
95  699448075545857                     {'thích': 716, 'yêu thích': 8}
96  700915848732413  {'thích': 702, 'yêu thích': 11, 'thương thương...
97  700496968774301  {'thích': 695, 'yêu thích': 89, 'haha': 4, 'wo...
98  699975425493122  {'thích': 620, 'yêu thích': 13, 'wow': 1, 'thư...
99  699954578828540  {'thích': 648, 'yêu thích': 9, 'haha': 1, 'wow...

[100 rows x 2 columns]

In ra time, tamstamp

In [21]:
df_time = df[['time','timestamp','reaction_count']][:100]
print(df_time)

                   time     timestamp  reaction_count
0   2023-11-28 15:29:55  1.701160e+09              46
1   2023-11-27 18:11:42  1.701084e+09             268
2   2023-11-27 09:45:00  1.701053e+09              15
3   2023-11-24 17:12:20  1.700821e+09              57
4   2023-11-24 10:00:24  1.700795e+09             493
..                  ...           ...             ...
95  2023-09-22 15:00:35  1.695370e+09             724
96  2023-09-22 10:00:02  1.695352e+09             714
97  2023-09-21 15:00:03  1.695283e+09             794
98  2023-09-20 14:56:20  1.695197e+09             637
99  2023-09-20 14:00:01  1.695193e+09             664

[100 rows x 3 columns]

Thay thế nội dung hiện [] bằng giá trị NaN

In [22]:
columns_NaN = ['images', 'images_description', 'comments_full', 'reactors']
Clean_data_df[columns_NaN] = Clean_data_df[columns_NaN].apply(lambda x: x.replace('[]', np.nan))
# Đưa ra file clean
Clean_data_df.to_csv('clean_data.csv', index=False)

Xóa các cột không cần thiết

In [23]:
# Lấy danh sách các cột bạn muốn xóa
columns_drop = ["image", "image_lowquality","images","video","video_id",
                "shared_text","timestamp", "shared_post_id", "shared_time",
                "shared_user_id", "shared_username", "shared_post_url", "with", "sharers"]
# Kiểm tra xem các cột có tồn tại trong DataFrame không
existing_columns = set(columns_drop).intersection(df.columns)
# Xóa các cột tồn tại
Clean_data_df = df.drop(existing_columns, axis=1)

# Tiền Xử Lý Dữ Liệu:

Tách cột reactions và gộp với post_text, shares,comments, reactions_count

In [24]:
import ast

In [25]:
df['reactions'] = df['reactions'].apply(lambda x: dict(ast.literal_eval(x)) if isinstance(x, str) else {})
raw_df_reactions = df['reactions'].apply(pd.Series )

In [26]:
df_with_reactions = pd.concat([df, raw_df_reactions], axis=1).drop('reactions', axis=1)
print(df_with_reactions[['post_text','thích','yêu thích','haha','wow','buồn','phẫn nộ','thương thương',
                                 'shares','comments','reaction_count']])

                                             post_text  thích  yêu thích  \
0    NGHE ĐỒN RIA MỞ QUÁN “CÀ HÊ” 👀\n\n😜 Ai đồn mà ...   33.0        9.0
1    Cảm ơn BAEMIN vì hành trình tuyệt vời vừa qua ...  179.0       76.0
2    Sáng chói cùng "Gà Mê Mật" của Lotteria 😍😍😍\n\...   11.0        1.0
3    🎉 CHÀO MỪNG SỰ TRỞ LẠI CỦA LOTTERIA ĐỒNG THÁP ...   49.0        7.0
4    🔥 SIÊU HỘI BLACK FRIDAY - ĂN GÀ RIA NO ĐẦY 🔥\n...  472.0       17.0
..                                                 ...    ...        ...
935  MĂM GÀ MỌI NƠI, FREESHIP TẬN CỬA\nO tròn như q...    NaN        NaN
936                                                NaN    NaN        NaN
937  Lại sắp hết tuần rồi, cùng Lotteria nạp mana g...    NaN        NaN
938  Tiết kiệm lên đến 42% nhanh tay chốt deal ngay...    NaN        NaN
939  SIÊU UP-SIZE, CHẲNG LO BỤNG ĐÓI\nĐi đâu mà vội...    NaN        NaN

     haha  wow  buồn  phẫn nộ  thương thương  shares  comments  reaction_count
0     2.0  2.0   NaN      NaN            NaN       6         0              46
1     NaN  1.0   3.0      NaN            9.0       9         3             268
2     2.0  1.0   NaN      NaN            NaN       0         0              15
3     NaN  NaN   NaN      NaN            1.0       2         1              57
4     NaN  2.0   1.0      NaN            1.0       4        20             493
..    ...  ...   ...      ...            ...     ...       ...             ...
935   NaN  NaN   NaN      NaN            NaN       0         0               0
936   NaN  NaN   NaN      NaN            NaN       0         0               0
937   NaN  NaN   NaN      NaN            NaN       0         0               0
938   NaN  NaN   NaN      NaN            NaN       0         0               0
939   NaN  NaN   NaN      NaN            NaN       0         0               0

[940 rows x 11 columns]

Thay thế giá trị NaN trong các cột bằng giá trị 0

In [27]:
columns_to_replace = ['post_text', 'thích', 'yêu thích', 'haha', 'wow', 'buồn', 'phẫn nộ', 'thương thương', 'shares', 'comments', 'reaction_count']

In [28]:
for column in columns_to_replace:
    df_with_reactions[column].fillna(0, inplace=True)

result_df = df_with_reactions[['post_text', 'thích', 'yêu thích', 'haha', 'wow', 'buồn', 'phẫn nộ', 'thương thương', 'shares', 'comments', 'reaction_count']]
result_df

,post_text,thích,yêu thích,haha,wow,buồn,phẫn nộ,thương thương,shares,comments,reaction_count
0,NGHE ĐỒN RIA MỞ QUÁN “CÀ HÊ” 👀\n\n😜 Ai đồn mà ...,33.0,9.0,2.0,2.0,0.0,0.0,0.0,6,0,46
1,Cảm ơn BAEMIN vì hành trình tuyệt vời vừa qua ...,179.0,76.0,0.0,1.0,3.0,0.0,9.0,9,3,268
2,"Sáng chói cùng ""Gà Mê Mật"" của Lotteria 😍😍😍\n\...",11.0,1.0,2.0,1.0,0.0,0.0,0.0,0,0,15
3,🎉 CHÀO MỪNG SỰ TRỞ LẠI CỦA LOTTERIA ĐỒNG THÁP ...,49.0,7.0,0.0,0.0,0.0,0.0,1.0,2,1,57
4,🔥 SIÊU HỘI BLACK FRIDAY - ĂN GÀ RIA NO ĐẦY 🔥\n...,472.0,17.0,0.0,2.0,1.0,0.0,1.0,4,20,493
...,...,...,...,...,...,...,...,...,...,...,...
935,"MĂM GÀ MỌI NƠI, FREESHIP TẬN CỬA\nO tròn như q...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
936,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
937,"Lại sắp hết tuần rồi, cùng Lotteria nạp mana g...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
938,Tiết kiệm lên đến 42% nhanh tay chốt deal ngay...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
939,"SIÊU UP-SIZE, CHẲNG LO BỤNG ĐÓI\nĐi đâu mà vội...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0

In [29]:
# chuyển time sang dạng datetime
Clean_data_df['time'] = pd.to_datetime(Clean_data_df['time'])

In [30]:
Clean_data_df['month'] = Clean_data_df['time'].dt.month
Clean_data_df['day']= Clean_data_df['time'].dt.day
Clean_data_df['year']=Clean_data_df['time'].dt.year
Clean_data_df[['day','month','year']]

     day  month  year
0     28     11  2023
1     27     11  2023
2     27     11  2023
3     24     11  2023
4     24     11  2023
..   ...    ...   ...
935   25      2  2022
936   24      2  2022
937   24      2  2022
938   23      2  2022
939   22      2  2022

[940 rows x 3 columns]